version: "2"

services:
    testapi:
        build: ./TestApi/
        depends_on:
            - cache
        ports:
            - "5000:5000"

    cache:
        image: redis:alpine
        expose:
            - "6379"
