version: "2"

services:
    dockerpoc:
        build: ./DotNetCoreDockerConsoleApp
        depends_on:
            - mycache

    mycache:
        image: redis:alpine
        expose:
            - "6379"
