version: "2"

services:
    ci-build:
        image: microsoft/dotnet:1.0.1-sdk-projectjson
        volumes:
            - ./DotNetCoreDockerConsoleApp:/src
        working_dir: /src
        command: /bin/bash -c "dotnet restore && dotnet publish -c Release -o bin ."
